# Cleaning and Data Analysis of Dog Licencing Data

In [41]:
import pandas as pd
import numpy as np

dog_data = pd.read_csv("NYC_Dog_Licensing_Dataset.csv")

In [42]:
dog_data

,RowNumber,AnimalName,AnimalGender,AnimalBirthMonth,BreedName,Borough,ZipCode,LicenseIssuedDate,LicenseExpiredDate,Extract Year
0,1,PAIGE,F,2014,American Pit Bull Mix / Pit Bull Mix,NaN,10035,09/12/2014,09/12/2017,2016
1,2,YOGI,M,2010,Boxer,NaN,10465,09/12/2014,10/02/2017,2016
2,3,ALI,M,2014,Basenji,NaN,10013,09/12/2014,09/12/2019,2016
3,4,QUEEN,F,2013,Akita Crossbreed,NaN,10013,09/12/2014,09/12/2017,2016
4,5,LOLA,F,2009,Maltese,NaN,10028,09/12/2014,10/09/2017,2016
5,6,IAN,M,2006,Unknown,NaN,10013,09/12/2014,10/30/2019,2016
6,7,BUDDY,M,2008,Unknown,NaN,10025,09/12/2014,10/20/2017,2016
7,8,CHEWBACCA,F,2012,Labrador Retriever Crossbreed,NaN,10013,09/12/2014,10/01/2019,2016
8,9,HEIDI-BO,F,2007,Dachshund Smooth Coat,NaN,11215,09/13/2014,04/16/2017,2016
9,10,MASSIMO,M,2009,"Bull Dog, French",NaN,11201,09/13/2014,09/17/2017,2016
10,11,LOLA,F,2006,Miniature Pinscher,NaN,10022,09/13/2014,10/03/2019,2016
11,12,LEMMY,F,2005,Yorkshire Terrier,NaN,10003,09/13/2014,10/26/2017,2016
12,13,LUCY,F,2014,Dachshund Smooth Coat Miniature,NaN,11215,09/13/2014,09/13/2019,2016
13,14,RICKY,M,2014,German Shepherd Dog,NaN,11220,09/13/2014,09/13/2017,2016
14,15,SARAH,F,2012,Unknown,NaN,10040,09/13/2014,09/13/2017,2016
15,16,MURPHY,M,2012,American Pit Bull Mix / Pit Bull Mix,NaN,10463,09/13/2014,09/28/2017,2016
16,17,JUNE,F,2010,Cavalier King Charles Spaniel,NaN,11238,09/13/2014,10/28/2019,2016
17,18,ELIZABETH,F,2013,Cavalier King Charles Spaniel,NaN,10022,09/13/2014,09/13/2019,2016
18,19,AVERY,F,2014,American Pit Bull Terrier/Pit Bull,NaN,10002,09/13/2014,09/13/2019,2016
19,20,SOPHIE,F,2011,Boxer,NaN,10308,09/13/2014,10/23/2019,2016
20,21,OTIS,F,2001,Unknown,NaN,10011,09/13/2014,09/29/2017,2016
21,22,BENSON,M,2010,Boxer,NaN,11209,09/13/2014,10/29/2019,2016
22,23,BIGS,M,2004,American Pit Bull Terrier/Pit Bull,NaN,11208,09/13/2014,10/27/2019,2016
23,24,LOGAN,M,2003,Unknown,NaN,10011,09/13/2014,10/30/2017,2016
24,25,BESS,F,2010,Beagle,NaN,11218,09/13/2014,09/13/2016,2016
25,26,APPLE,M,2013,Havanese,NaN,10025,09/13/2014,10/16/2019,2016
26,27,MUNECA,F,2013,Beagle,NaN,11232,09/13/2014,09/13/2019,2016
27,28,DOTTIE,F,2013,"Poodle, Standard",NaN,10025,09/13/2014,09/13/2017,2016
28,29,OSCAR,M,2008,German Shorthaired Pointer,NaN,10025,09/13/2014,09/13/2019,2016
29,30,BUDDY,M,2012,Bull Terrier,NaN,10312,09/13/2014,10/05/2019,2016
...,...,...,...,...,...,...,...,...,...,...
345697,117342,RUTH,F,2018,Labrador Retriever Crossbreed,NaN,10025,12/31/2018,12/31/2019,2018
345698,117343,SAMMIE,F,2018,Shih Tzu Crossbreed,NaN,10128,12/31/2018,12/31/2019,2018
345699,117344,LOLA,F,2017,Jack Russell Terrier,NaN,10703,12/31/2018,12/31/2019,2018
345700,117345,YOSHI,M,2016,Labrador Retriever Crossbreed,NaN,10024,12/31/2018,12/31/2021,2018
345701,117346,TOTO,F,2009,Cairn Terrier,NaN,10308,12/31/2018,11/30/2019,2018
345702,117347,SPIKE,M,2005,Pomeranian,NaN,10003,12/31/2018,01/30/2020,2018
345703,117348,SHILOH,F,2006,Unknown,NaN,11249,12/31/2018,11/29/2019,2018
345704,117349,PRADA,F,2010,Shih Tzu,NaN,11374,12/31/2018,12/29/2019,2018
345705,117350,APPA,M,2013,Goldendoodle,NaN,10027,12/31/2018,01/30/2020,2018
345706,117351,CUPID,M,2014,Jack Russell Terrier,NaN,10473,12/31/2018,12/23/2019,2018
345707,117352,WINNIE,M,2014,Chihuahua Crossbreed,NaN,11413,12/31/2018,12/05/2019,2018
345708,117353,TRIXIE,F,2013,Basset Hound,NaN,10307,12/31/2018,12/12/2019,2018
345709,117354,GAVIN,M,2015,Chihuahua,NaN,10016,12/31/2018,01/25/2020,2018
345710,117355,GRIFF,M,2012,Yorkshire Terrier Crossbreed,NaN,11201,12/31/2018,01/24/2020,2018
345711,117356,PIPA,M,2015,Pug,NaN,11366,12/31/2018,02/19/2021,2018
345712,117357,LEXI,F,2014,Jack Russell Terrier,NaN,11219,12/31/2018,02/13/2020,2018
345713,117358,BELLA,F,2009,Yorkshire Terrier,NaN,10029,12/31/2018,12/13/2019,2018
345714,117359,DUSTY,F,2008,Norfolk Terrier,NaN,10028,12/31/2018,12/10/2019,2018
345715,117360,BELLA,F,2010,Chihuahua,NaN,10463,12/31/2018,02/17/2020,2018
345716,117361,SHEA,F,2013,Golden Retriever,NaN,11377,12/31/2018,02/08/2020,2018
345717,117362,OTIS,M,2011,Rottweiler,NaN,10075,12/31/2018,01/27/2020,2018
345718,117363,DEXTER,M,2010,Unknown,NaN,10009,12/31/2018,10/21/2019,2018
345719,117364,ERNIE,M,2016,Labrador Retriever,NaN,11249,12/31/2018,12/31/2020,2018
345720,117365,HUGO,M,2018,Poodle,NaN,11217,12/31/2018,12/31/2019,2018
345721,117366,TOBY,M,2018,Maltese,NaN,10470,12/31/2018,12/31/2019,2018
345722,117367,BOLAND,F,2018,Pomeranian,NaN,10306,12/31/2018,12/31/2019,2018
345723,117368,UNKNOWN,M,2018,Australian Shepherd,NaN,11233,12/31/2018,12/31/2019,2018
345724,117369,UNKNOWN,F,2018,Dachshund,NaN,10454,12/31/2018,12/31/2019,2018
345725,117370,LUNA,F,2018,Jindo,NaN,11385,12/31/2018,12/31/2019,2018
345726,117371,HUNTER,M,2017,Siberian Husky,NaN,10456,12/31/2018,12/31/2019,2018

## Getting Initial Statistics

In [43]:
len(dog_data)

345727

In [44]:
#almost 30,000 unknowns, lets clean those up
dog_data = dog_data[dog_data["BreedName"] != "Unknown"]

In [45]:
dog_data = dog_data[dog_data["ZipCode"] >9999]

In [46]:
len(dog_data)

306865

## Data Cleaning

### Getting the Boroughs

In [47]:
bronx = [10453, 10457, 10460, 10458, 10467, 10468, 10451, 10452, 10456, 10454, 10455, 10459, 10474, 10463, 10471, 10466, 10469, 10470, 10475, 10461, 10462,10464, 10465, 10472, 10473]
brooklyn = [11212, 11213, 11216, 11233, 11238, 11209, 11214, 11228, 11204, 11218, 11219, 11230, 11234, 11236, 11239, 11223, 11224, 11229, 11235, 11201, 11205, 11215, 11217, 11231, 11203, 11210, 11225, 11226, 11207, 11208, 11211, 11222, 11220, 11232, 11206, 11221, 11237]
manhattan = [10026, 10027, 10030, 10037, 10039, 10001, 10011, 10018, 10019, 10020, 10036, 10029, 10035, 10010, 10016, 10017, 10022, 10012, 10013, 10014, 10004, 10005, 10006, 10007, 10038, 10280, 10002, 10003, 10009, 10021, 10028, 10044, 10065, 10075, 10128, 10023, 10024, 10025, 10031, 10032, 10033, 10034, 10040]
queens = [11361, 11362, 11363, 11364, 11354, 11355, 11356, 11357, 11358, 11359, 11360, 11365, 11366, 11367, 11412, 11423, 11432, 11433, 11434, 11435, 11436, 11101, 11102, 11103, 11104, 11105, 11106, 11374, 11375, 11379, 11385, 11691, 11692, 11693, 11694, 11695, 11697, 11004, 11005, 11411, 11413, 11422, 11426, 11427, 11428, 11429, 11414, 11415, 11416, 11417, 11418, 11419, 11420, 11421, 11368, 11369, 11370, 11372, 11373, 11377, 11378]
staten_island = [10302, 10303, 10310, 10306, 10307, 10308, 10309, 10312, 10301, 10304, 10305, 10314]

In [48]:
def get_boroughs(data, bronx, brooklyn, manhattan, queens, staten_island):
    ans = []
    for ind, row in data.iterrows(): 
        zips = row["ZipCode"]
        if zips in bronx:
            ans.append("Bronx")
        elif zips in brooklyn:
            ans.append("Brooklyn")
        elif zips in manhattan:
            ans.append("Manhattan")
        elif zips in queens:
            ans.append("Queens")
        elif zips in staten_island:
            ans.append("Staten Island")
        else:
            ans.append(np.nan)
    return ans

In [49]:
dog_data["Borough"] = get_boroughs(dog_data, bronx, brooklyn, manhattan, queens, staten_island)

In [50]:
dog_data.head()

,RowNumber,AnimalName,AnimalGender,AnimalBirthMonth,BreedName,Borough,ZipCode,LicenseIssuedDate,LicenseExpiredDate,Extract Year
0,1,PAIGE,F,2014,American Pit Bull Mix / Pit Bull Mix,Manhattan,10035,09/12/2014,09/12/2017,2016
1,2,YOGI,M,2010,Boxer,Bronx,10465,09/12/2014,10/02/2017,2016
2,3,ALI,M,2014,Basenji,Manhattan,10013,09/12/2014,09/12/2019,2016
3,4,QUEEN,F,2013,Akita Crossbreed,Manhattan,10013,09/12/2014,09/12/2017,2016
4,5,LOLA,F,2009,Maltese,Manhattan,10028,09/12/2014,10/09/2017,2016

In [51]:
dog_data = dog_data[dog_data["Borough"] != np.nan]

In [52]:
len(dog_data)

306865

In [65]:
dog_data.groupby("BreedName").count().sort_values(by="RowNumber", ascending=False)

,RowNumber,AnimalName,AnimalGender,AnimalBirthMonth,Borough,ZipCode,LicenseIssuedDate,LicenseExpiredDate,Extract Year
BreedName,,,,,,,,,
Yorkshire Terrier,21920,21820,21917,21920,21644,21920,21920,21920,21920
Shih Tzu,19619,19583,19616,19619,19396,19619,19619,19619,19619
Chihuahua,15644,15622,15644,15644,15450,15644,15644,15644,15644
Maltese,11390,11363,11387,11390,11249,11390,11390,11390,11390
Labrador Retriever,11323,11320,11323,11323,11126,11323,11323,11323,11323
American Pit Bull Mix / Pit Bull Mix,10303,10303,10303,10303,10207,10303,10303,10303,10303
Labrador Retriever Crossbreed,8511,8509,8511,8511,8367,8511,8511,8511,8511
American Pit Bull Terrier/Pit Bull,8319,8319,8319,8319,8260,8319,8319,8319,8319
Pomeranian,6342,6319,6342,6342,6208,6342,6342,6342,6342
Havanese,5909,5897,5909,5909,5783,5909,5909,5909,5909
Beagle,5784,5773,5784,5784,5699,5784,5784,5784,5784
Jack Russell Terrier,5347,5328,5347,5347,5276,5347,5347,5347,5347
Golden Retriever,5184,5176,5184,5184,5081,5184,5184,5184,5184
German Shepherd Dog,5113,5107,5110,5113,5052,5113,5113,5113,5113
Shih Tzu Crossbreed,5025,4998,5025,5025,4961,5025,5025,5025,5025
Chihuahua Crossbreed,4685,4684,4685,4685,4600,4685,4685,4685,4685
Cocker Spaniel,4359,4342,4359,4359,4299,4359,4359,4359,4359
French Bulldog,4257,4249,4257,4257,4109,4257,4257,4257,4257
German Shepherd Crossbreed,4214,4214,4214,4214,4154,4214,4214,4214,4214
Shiba Inu,4209,4196,4209,4209,4114,4209,4209,4209,4209
Cavalier King Charles Spaniel,3975,3969,3972,3975,3880,3975,3975,3975,3975
Pug,3940,3937,3940,3940,3884,3940,3940,3940,3940
Siberian Husky,3508,3473,3508,3508,3461,3508,3508,3508,3508
"Poodle, Toy",3494,3490,3494,3494,3402,3494,3494,3494,3494
Poodle Crossbreed,3448,3409,3448,3448,3386,3448,3448,3448,3448
Boston Terrier,3428,3412,3428,3428,3366,3428,3428,3428,3428
"Poodle, Miniature",3331,3330,3331,3331,3279,3331,3331,3331,3331
Terrier mix,3233,3233,3233,3233,3175,3233,3233,3233,3233
Bichon Frise,3130,3122,3130,3130,3098,3130,3130,3130,3130
Yorkshire Terrier Crossbreed,3025,2983,3025,3025,2985,3025,3025,3025,3025
...,...,...,...,...,...,...,...,...,...
Kromfohrlander,7,7,7,7,7,7,7,7,7
Pumi,7,7,7,7,7,7,7,7,7
Cirneco dell,7,7,7,7,7,7,7,7,7
Wirehaired Vizsla,6,6,6,6,6,6,6,6,6
Kai Ken,6,6,6,6,5,6,6,6,6
Swedish Vallhund,6,6,6,6,6,6,6,6,6
Beauceron,5,5,5,5,5,5,5,5,5
Icelandic Sheepdog,5,5,5,5,5,5,5,5,5
Small Munsterlander Pointer,4,4,4,4,4,4,4,4,4
Otterhound,4,4,4,4,4,4,4,4,4
American Leopard Hound,4,4,4,4,4,4,4,4,4
Peruvian Inca Orchid,3,3,3,3,3,3,3,3,3
Grand Basset Griffon Vendeen,3,3,3,3,3,3,3,3,3
Bracco Italiano,3,3,3,3,3,3,3,3,3
Cesky Terrier,3,3,3,3,3,3,3,3,3
Norwegian Buhund,3,3,3,3,3,3,3,3,3
Baladi,2,2,2,2,2,2,2,2,2
Finnish Lapphund,2,2,2,2,2,2,2,2,2
Mountain Feist,2,2,2,2,2,2,2,2,2
Jagdterrier,2,2,2,2,2,2,2,2,2
Estrela Mountain Dog,2,2,2,2,2,2,2,2,2
English Setter Crossbreed,2,2,2,2,2,2,2,2,2
Hamiltonstovare,2,2,2,2,2,2,2,2,2
Russian Wolfhound,2,2,2,2,2,2,2,2,2
Belgian Laekenois,2,2,2,2,2,2,2,2,2
Azawakh,1,1,1,1,1,1,1,1,1
Stabyhoun,1,1,1,1,1,1,1,1,1
Tosa,1,1,1,1,1,1,1,1,1
Portuguese Sheepdog,1,1,1,1,1,1,1,1,1
Karelian Bear Dog,1,1,1,1,1,1,1,1,1

In [66]:
dog_data.to_csv("cleaned_pet_data.csv")